name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.2-jdk17

    steps:
    - uses: actions/checkout@v4

    - name: Build Debug APK
      run: gradle assembleDebug --no-daemon --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: daojiary-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Build Release APK
      run: gradle assembleRelease --no-daemon --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: daojiary-release
        path: app/build/outputs/apk/release/app-release.apk
